<?php

use Illuminate\Database\Seeder;

class FilmsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('films')->delete();

        $genreterror = DB::table('genres')->where('genre','Terror')->first();
        $genrefantasia = DB::table('genres')->where('genre','Fantasía')->first();
        $genreaccion = DB::table('genres')->where('genre','Acción')->first();
        $genrecrimen = DB::table('genres')->where('genre','Crimen')->first();
        $genrecficcion = DB::table('genres')->where('genre','Ciencia ficción')->first();
        $genredrama = DB::table('genres')->where('genre','Drama')->first();
        $genresuspense = DB::table('genres')->where('genre','Suspense')->first();
        $genrecomedia = DB::table('genres')->where('genre','Comedia')->first();
        $genremisterio = DB::table('genres')->where('genre','Misterio')->first();
        $genrecinenegro = DB::table('genres')->where('genre','Cine negro')->first();

        DB::table('films')->insert(
            [
                ['trailer' => 'https://www.youtube.com/watch?v=WrFTmZwe5wc' , 'name'=> 'Saw','year' => 2004,'description' => 'Adam se despierta encadenado a un tubo oxidado dentro de una decrépita cámara subterránea. A su lado, hay otra persona encadenada, el Dr. Lawrence Gordon. Entre ellos hay un hombre muerto. Ninguno de los dos sabe por qué está allí, pero tienen un casette con instrucciones para que el Dr. Gordon mate a Adam en un plazo de ocho horas. Recordando una investigación de asesinato llevada a cabo por un detective llamado Tapp, Gordon descubre que él y Adam son victimas de un psicópata conocido como Jigsaw. Sólo disponen de unas horas para desenredar el complicado rompecabezas en el que están inmersos.' ,'country' =>'USA', 'director' =>'James Wan', 'rating' => 7,'genre_id'=>$genreterror->id],
                ['trailer' => 'https://www.youtube.com/watch?v=M1MNb836IGw' ,'name'=> 'Celda 211','year' => 2009,'description' => 'El día en que Juan (Alberto Ammann) empieza a trabajar en su nuevo destino como funcionario de prisiones, se ve atrapado en un motín carcelario. Decide entonces hacerse pasar por un preso más para salvar su vida y para poner fin a la revuelta, encabezada por el temible Malamadre (Luis Tosar). Lo que ignora es que el destino le ha preparado una encerrona.','country' =>'España', 'director' =>'Daniel Monzon','rating' => 8,'genre_id'=>$genresuspense->id],
                ['trailer' => 'https://www.youtube.com/watch?v=neY2xVmOfUM' ,'name'=> 'Batman Begins','year' => 2005,'description' => 'Nueva adaptación del famoso cómic. Narra los orígenes de la leyenda de Batman y los motivos que lo convirtieron en el representante del Bien en la ciudad de Gotham. Bruce Wayne vive obsesionado con el recuerdo de sus padres, muertos a tiros en su presencia. Atormentado por el dolor, se va de Gotham y recorre el mundo hasta que encuentra a un extraño personaje que lo adiestra en todas las disciplinas físicas y mentales que le servirán para combatir el Mal. Por esta razón, la Liga de las Sombras, una poderosa y subversiva sociedad secreta, dirigida por el enigmático Ras Al Ghul, intenta reclutarlo. Cuando Bruce vuelve a Gotham, la ciudad está dominada por el crimen y la corrupción. Con la ayuda de su leal mayordomo Alfred, del detective de la policía Jim Gordon y de Lucius Fox, su colega en una Sociedad de Ciencias Aplicadas, Wayne libera a su alter ego: Batman, un justiciero enmascarado que utiliza la fuerza, la inteligencia y la más alta tecnología para luchar contra las siniestras fuerzas que amenazan con destruir la ciudad.','country'=>'USA', 'director' =>'Christopher Nolan', 'rating' => 9,'genre_id'=>$genrefantasia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=6LRLSvIioWs' ,'name'=> 'Snatch. Cerdos y diamantes','year' => 2000,'description' => 'Franky es un ladrón de diamantes que tiene que entregar un valioso ejemplar a su jefe Avi, pero, antes de hacerlo, se deja convencer por un tal Boris para apostar en un combate ilegal de boxeo. En realidad, se trata de una trampa para arrebatarle el diamante. Cuando Avi se entera, contrata a Tony para encontrar a Franky y al diamante. Descubierto el triste destino de Franky, la recuperación de la gema desaparecida provoca una situación caótica, donde el engaño, el chantaje y el fraude se mezclan de forma sangrienta con perros, diamantes, boxeadores y gran variedad de armas.' ,'country'=>'USA', 'director' =>'Guy Ritchie', 'rating' => 9,'genre_id'=>$genrecrimen->id],
                ['trailer' => 'https://www.youtube.com/watch?v=VVwqTv1nMTA' ,'name'=> 'RocknRolla','year' => 2008,'description' => 'La noticia de que Uri Omovich (Karel Roden), un rico mafioso ruso, está montando un negocio multimillonario de compraventa ilegal de terrenos en Londres, hará que todos los delincuentes de la ciudad quieran participar en la operación. Uri le pide a Lenny Cole (Tom Wilkinson), un pez gordo de la mafia londinense, que se ocupe de todos los trámites burocráticos y compré a un concejal (Jimi Mistry). Lenny confía la operación a su lugarteniente Archy (Mark Strong). Por su parte, la contable de Uri, Stella (Thandie Newton), decide llevarse parte del botín; para ello, contrata a dos mafiosos, que tienen cuentas pendientes con Lenny. ','country' =>'USA', 'director' =>'Guy Ritchie', 'rating' => 8,'genre_id'=>$genrecrimen->id],
                ['trailer' => 'https://www.youtube.com/watch?v=imm6OR605UI' ,'name'=> 'Oceans Eleven','year' => 2001,'description' => 'Danny Ocean es un carismático ladrón que, tan sólo 24 horas después de cumplir una larga condena en prisión, ya está planeando su próximo delito. Su objetivo: realizar el mayor atraco de casinos de la historia. Para ello formará un equipo de once hombres, cada uno de ellos el mejor en su campo. Sin embargo surgirá un problema inesperado: el dueño de los locales, Terry Benedic, está saliendo con Tess, su ex-mujer. ', 'country'=>'USA', 'director' =>'Steven soderbergh', 'rating' => 7,'genre_id'=>$genreaccion->id],
                ['trailer' => 'https://www.youtube.com/watch?v=3skO4UOtUDs' ,'name'=> 'El caso Slevin','year' => 2006,'description' => 'A Slevin la vida no le va nada bien: después de perder su trabajo y que su casa sea declarada en ruinas, encuentra a su novia con otro en la cama. Desesperado, decide irse de Los Ángeles una temporada y alojarse en el apartamento que un amigo tiene en Nueva York. Pero la auténtica pesadilla de Slevin empezará cuando se vea involucrado en el sórdido mundo de la mafia neoyorquina. Los dos gánsteres más respetados y temidos de la ciudad, El Rabino y El Jefe, antes socios y ahora enemigos acérrimos, viven atrincherados en sus fortalezas y llevan 20 años sin salir de ellas. Para vengar el asesinato de su hijo, El Jefe planea matar al hijo del Rabino, pero sin dejar huellas, pues, en caso contrario, estallaría una sangrienta guerra entre los dos clanes. El plan consiste en buscar un jugador que le deba mucho dinero al Jefe y encargarle el asunto.','country' =>'USA', 'director' =>'Paul McGuigan', 'rating' => 8,'genre_id'=>$genrecrimen->id],
                ['trailer' => 'https://www.youtube.com/watch?v=aReggdebpTE' ,'name'=> 'Hancock','year' =>2008,'description' => 'Hancock (Will Smith), una especie de héroe bastante impopular, se siente insatisfecho, atormentado e incomprendido. Con sus acciones heroicas, consigue salvar muchas vidas, pero, al mismo tiempo, provoca auténticas catástrofes. Aunque, en general, la población le está agradecida, la mayoría de los habitantes de Los Ángeles no puede soportarlo. Un día en que le salva la vida a Ray Embrey (Jason Bateman), un alto ejecutivo de una empresa de relaciones públicas, Hancock se da cuenta de que es un ser vulnerable.','country' =>'USA', 'director' =>'Peter Berf', 'rating' => 8,'genre_id'=>$genrefantasia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=jSJKgHLlRFQ' ,'name'=> 'Hijos de los hombres','year' => 2006,'description' => 'Año 2027: el ser humano está al borde de la extinción: los hombres han perdido la capacidad de procrear y se ignora por qué razon todas las mujeres del planeta se han vuelto estériles. Al mismo tiempo, el mundo se estremece cuando muere un muchacho de 18 años, la persona más joven de la Tierra. Se vive, pues, una situación de caos galopante. En tales circunstancias, Theo (Clive Owen), un desilusionado ex-activista radical de Londres convertido en burócrata, es contratado por Julian (Julianne Moore) para que proteja a una mujer que puede tener el secreto de la salvación de la humanidad, la persona más valiosa de la Tierra... ','country' =>'Reino Unido', 'director' =>'Alfonso Cuaron', 'rating' => 7,'genre_id'=>$genrecficcion->id],
                ['trailer' => 'https://www.youtube.com/watch?v=h-9RYiqyqjk' ,'name'=> 'Señor de los anillos,El retorno del Rey','year' => 2003,'description' => 'Las fuerzas de Saruman han sido destruidas, y su fortaleza sitiada. Ha llegado el momento de decidir el destino de la Tierra Media, y, por primera vez, parece que hay una pequeña esperanza. El interés del señor oscuro Sauron se centra ahora en Gondor, el último reducto de los hombres, cuyo trono será reclamado por Aragorn. Sauron se dispone a lanzar un ataque decisivo contra Gondor. Mientras tanto, Frodo y Sam continuan su camino hacia Mordor, con la esperanza de llegar al Monte del Destino.','country' =>'USA', 'director' =>'Peter Jackson', 'rating' => 9,'genre_id'=>$genrefantasia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=H8jdu47CUV8' ,'name'=> 'Harry Potter y la piedra filosofal','year' => 1997,'description' => 'El día en que cumple once años, Harry Potter se entera de que es hijo de dos destacados hechiceros, de los que ha heredado poderes mágicos. En la escuela Hogwarts de Magia y Hechicería, donde se educa con otros niños que también tienen poderes especiales, aprenderá todo lo necesario para ser mago. ','country' =>'USA', 'director' =>'Chris Columbus', 'rating' => 10,'genre_id'=>$genrecficcion->id],
                ['trailer' => 'https://www.youtube.com/watch?v=VYI5-POKvnA' ,'name'=> 'El exorcista','year' => 1975,'description' => 'Adaptación de la novela de William Peter Blatty que se inspiró en un exorcismo real ocurrido en Washington en 1949. Regan, una niña de doce años, es víctima de fenómenos paranormales como la levitación o la manifestación de una fuerza sobrehumana. Su madre, aterrorizada, tras someter a su hija a múltiples análisis médicos que no ofrecen ningún resultado, acude a un sacerdote con estudios de psiquiatría. Éste, convencido de que el mal no es físico sino espiritual, es decir que se trata de una posesión diabólica, decide practicar un exorcismo. Seguramente la película de terror más popular de todos los tiempos.','country' =>'USA', 'director' =>'William Friedkin', 'rating' => 8,'genre_id'=>$genreterror->id],
                ['trailer' => 'https://www.youtube.com/watch?v=hEsJwy3OBi4' ,'name'=> 'Ouija, El origen del mal','year' => 2016,'description' => 'Cuenta la historia de una madre viuda y sus dos hijas, quienes añaden un nuevo truco para reforzar su estafador negocio de espiritismo, invitando involuntariamente al auténtico demonio a entrar en su casa. Cuando la hija pequeña, es poseída por este espíritu despiadado, la familia se tendrá que enfrentar a sus temores más impensables para poder salvarla y enviar al diablo de vuelta al otro lado','country' =>'USA', 'director' =>'Mike Flanagan', 'rating' => 6,'genre_id'=>$genresuspense->id],
                ['trailer' => 'https://www.youtube.com/watch?v=mvEetUDCKxE' ,'name'=> 'No respires','year' => 2016,'description' => 'Unos jóvenes ladrones creen haber encontrado la oportunidad de cometer el robo perfecto. Su objetivo será un ciego solitario, poseedor de miles de dólares ocultos. Pero tan pronto como entran en su casa serán conscientes de su error, pues se encontrarán atrapados y luchando por sobrevivir contra un psicópata con sus propios y temibles secretos.','country' =>'USA', 'director' =>'Fede Álvarez', 'rating' => 7,'genre_id'=>$genresuspense->id],
                ['trailer' => 'https://www.youtube.com/watch?v=nQY6D8aywLs' ,'name'=> 'Lobezno 3','year' => 2017,'description' => 'Sin sus poderes, por primera vez, Wolverine es verdaderamente vulnerable. Después de una vida de dolor y angustia, sin rumbo y perdido en el mundo donde los X-Men son leyenda, su mentor Charles Xavier lo convence de asumir una última misión: proteger a una joven que será la única esperanza para la raza mutante... Tercera y última película protagonizada por Hugh Jackman en el papel de Lobezno. ','country' =>'USA', 'director' =>'James Mangold', 'rating' => 6,'genre_id'=>$genreaccion->id],
                ['trailer' => 'https://www.youtube.com/watch?v=74uOe8Oxwmo' ,'name'=> 'Torrente 5, Operación Eurovegas','year' => 2014,'description' => 'Año 2018. Torrente sale de la cárcel, y se encuentra aturdido ante una España convulsa y dividida. Debe encontrar respuestas en su interior para despejar su confusión, y por ello decide convertirse en un "fuera de la ley". Así que se propone atracar un casino con una banda de incompetentes. A través de un contacto de su estancia en prisión, localiza a John Marshall, la persona que se ocupó de supervisar la seguridad cuando se planificó el principal casino-hotel de Eurovegas. Marshall, el más indicado para planificar un golpe, le explica la necesidad de organizar una banda de especialistas, que Torrente se encargará de reclutar entre sus "contactos". ','country' =>'España', 'director' =>'Santiago Segura', 'rating' => 5,'genre_id'=>$genrecomedia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=uVQf5hGhB0c' ,'name'=> 'Solo en casa','year' => 1990,'description' => 'Kevin McAllister es un niño de ocho años, miembro de una familia numerosa, que accidentalmente se queda abandonado en su casa cuando toda la familia se marcha a pasar las vacaciones a Francia. Kevin aprende a valerse por sí mismo e incluso a protegerse de Harry y Marv, dos bribones que se proponen asaltar todas las casas cerradas de su vecindario. en cuanto su madre lo echa en falta, regresa apresuradamente a Chicago para recuperar a su hijo.','country' =>'USA', 'director' =>'Chris Columbus', 'rating' => 8,'genre_id'=>$genrecomedia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=w9bSO1hPq7w' ,'name'=> 'Sully, Hazaña en el Hudson','year' => 2016,'description' => 'Chesley “Sully” Sullenberger es un piloto aéreo que en 2009 se convirtió en un héroe cuando, al poco de despegar, su avión se averió y logró realizar un aterrizaje forzoso del aparato en pleno río Hudson, en Nueva York, con 155 pasajeros a bordo','country' =>'USA', 'director' =>'Clint Eastwood', 'rating' => 7,'genre_id'=>$genredrama->id],
                ['trailer' => 'https://www.youtube.com/watch?v=Cyh1LpxnaxI' ,'name'=> 'Forrest Gump','year' => 1994,'description' => 'Forrest Gump (Tom Hanks) sufre desde pequeño un cierto retraso mental. A pesar de todo, gracias a su tenacidad y a su buen corazón será protagonista de acontecimientos cruciales de su país durante varias décadas. Mientras pasan por su vida multitud de cosas en su mente siempre está presente la bella Jenny (Robin Wright), su gran amor desde la infancia, que junto a su madre será la persona más importante en su vida.','country' =>'USA', 'director' =>'Robert Zemeckis', 'rating' => 8,'genre_id'=>$genredrama->id],
                ['trailer' => 'https://www.youtube.com/watch?v=zfOdk9JDzSw' ,'name'=> 'El sexto sentido','year' => 1999,'description' => 'El doctor Malcom Crowe es un conocido psicólogo infantil de Philadelphia que vive obsesionado por el doloroso recuerdo de un joven paciente desequilibrado al que fue incapaz de ayudar. Cuando conoce a Cole Sear, un aterrorizado y confuso niño de ocho años que necesita tratamiento, ve que se le presenta la oportunidad de redimirse haciendo todo lo posible por ayudarlo. Sin embargo, el doctor Crowe no está preparado para conocer la terrible verdad acerca del don sobrenatural de su paciente: recibe visitas no deseadas de espíritus atormentados.','country' =>'USA', 'director' =>'M. Night Shyamalan', 'rating' => 9,'genre_id'=>$genremisterio->id],
                ['trailer' => 'https://www.youtube.com/watch?v=OzDKmB6bfQQ' ,'name'=> 'El beso de la muerte','year' => 1947,'description' => 'Un delincuente de Nueva York, Nick Bianco (Victor Mature) es herido y arrestado durante un asalto a una joyería. En el juicio, el fiscal Louis De Angelo (Brian Donlevy) le ofrece reducir su condena, si entrega los nombres de sus compinches, pero Nick se niega a ello. Después de tres años en prisión, Nick se entera de que su esposa se ha suicidado y sus dos hijas están en un orfanato. Decide entonces negociar con el fiscal De Angelo y entregar los nombres de sus cómplices. Sin embargo, el fiscal le exige que colabore también en la captura de Tommy Udo (Richard Widmark), un asesino y psicópata, cosa que el acepta. Nick es liberado y logra rehacer su vida con una nueva esposa y sus hijas. Pero Tommy Udo es liberado, y Nick comprende que lo buscará para tomar venganza.En 1995 el realizador Barbet Schroeder dirigió un remake protagonizado por Nicolas Cage.','country' =>'USA', 'director' =>'Henry Hathaway', 'rating' => 4,'genre_id'=>$genrecinenegro->id],
                ['trailer' => 'https://www.youtube.com/watch?v=ft8-IJ-vFr4' ,'name'=> 'Resident Evil, Capitulo final','year' => 2017,'description' => 'La humanidad está agonizando tras la traición sufrida por Alice a manos de Wesker. Alice deberá regresar a donde la comenzó la pesadilla -Raccoon City-, ya que allí la Corporación Umbrella está reuniendo fuerzas antes de un último ataque a los últimos supervivientes del apocalipsis. En una carrera contra el tiempo, Alice tendrá que unir fuerzas con viejos amigos y con un inesperado aliado en una batalla contra hordas de zombis y nuevos monstruos mutantes. Será la aventura más difícil de Alice para salvar a la humanidad, que está al borde de la extinción.','country' =>'Canadá', 'director' =>'Paul W.S. Anderson', 'rating' => 8,'genre_id'=>$genreterror->id],
                ['trailer' => 'https://www.youtube.com/watch?v=wqwmM1-7rSA' ,'name'=> 'Hombres de negro 3','year' => 2012,'description' => 'Cuando el MIB recibe la información de que el Agente K podría morir a manos de un alienígena, lo que cambiaría la historia para siempre, el Agente J es enviado a los años 60 para evitarlo. Tercera entrega de la popular saga Men in Black. ','country' =>'USA', 'director' =>'Barry Sonnenfeld', 'rating' => 6,'genre_id'=>$genrecficcion->id],
                ['trailer' => 'https://www.youtube.com/watch?v=ZFYCXAG6fdo' ,'name'=> 'Pulp Fiction','year' => 1994,'description' => 'Jules y Vincent, dos asesinos a sueldo con no demasiadas luces, trabajan para el gángster Marsellus Wallace. Vincent le confiesa a Jules que Marsellus le ha pedido que cuide de Mia, su atractiva mujer. Jules le recomienda prudencia porque es muy peligroso sobrepasarse con la novia del jefe. Cuando llega la hora de trabajar, ambos deben ponerse "manos a la obra". Su misión: recuperar un misterioso maletín','country' =>'USA', 'director' =>'Quentin Tarantino', 'rating' => 10,'genre_id'=>$genrecrimen->id],
                ['trailer' => 'https://www.youtube.com/watch?v=Lxx-cLKPYAY' ,'name'=> 'Mechanic, Resurrection','year' => 2016,'description' => 'Cuando Arthur Bishop (Jason Statham) creía que ya había dejado atrás su pasado criminal, se encuentra de nuevo con él al ser secuestrada la mujer de su vida por uno de sus mayores enemigos. Se ve así obligado a viajar por el mundo para ejecutar tres asesinatos imposibles que deben parecer accidentes.','country' =>'USA', 'director' =>'Dennis Gansel', 'rating' => 7,'genre_id'=>$genreaccion->id],
                ['trailer' => 'https://www.youtube.com/watch?v=jhgmy9HH99Q' ,'name'=> 'Fast & Furious 7','year' => 2015,'description' => 'Ha pasado un año desde que el equipo de Dominic Torreto y Brian pudiera regresar finalmente a Estados Unidos, tras ser indultados. Desean adaptarse a una vida en la legalidad, pero el entorno ya no es el mismo. Dom intenta acercarse a Letty, y Brian lucha para acostumbrarse a la vida en una urbanización con Mia y su hijo. Ninguno de ellos imagina que un frío asesino británico, entrenado para realizar operaciones secretas, se cruzará en sus vidas para convertirse en su mayor enemigo. ','country' =>'USA', 'director' =>'James Wan', 'rating' => 6,'genre_id'=>$genreaccion->id],
                ['trailer' => 'https://www.youtube.com/watch?v=1-fubC9JN50' ,'name'=> 'Un monstruo viene a verme','year' => 2016,'description' => 'Tras la separación de sus padres, Connor (Lewis MacDougall), un chico de 12 años, tendrá que ocuparse de llevar las riendas de la casa, pues su madre (Felicity Jones) está enferma de cáncer. Así las cosas, el niño intentará superar sus miedos y fobias con la ayuda de un monstruo (Liam Neeson), pero sus fantasías tendrán que enfrentarse no sólo con la realidad, sino con su fría y calculadora abuela (Sigourney Weaver). Con este nuevo trabajo J.A. Bayona cierra su trilogía sobre las relaciones maternofiliales, que inició con "El orfanato" y continuó con "Lo imposible". ','country' =>'España', 'director' =>'J.A. Bayona', 'rating' => 8,'genre_id'=>$genrefantasia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=YfopzNHLp4o' ,'name'=> 'Ocho apellidos vascos','year' => 2014,'description' => 'Rafa (Dani Rovira) es un joven señorito andaluz que no ha tenido que salir jamás de su Sevilla natal para conseguir lo único que le importa en la vida: el fino, la gomina, el Betis y las mujeres. Todo cambia cuando conoce una mujer que se resiste a sus encantos: es Amaia (Clara Lago), una chica vasca. Decidido a conquistarla, se traslada a un pueblo de las Vascongadas, donde se hace pasar por vasco para vencer su resistencia. Adopta el nombre de Antxon y varios apellidos vascos: Arguiñano, Igartiburu, Erentxun, Gabilondo, Urdangarín, Otegi, Zubizarreta... y Clemente. ','country' =>'España', 'director' =>'Emilio Martínez-Lázaro', 'rating' => 9,'genre_id'=>$genrecomedia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=X_jZHkOYSIg' ,'name'=> 'Tengo ganas de ti','year' => 2012,'description' => 'Secuela de "Tres metros sobre el cielo". La sexy Gin (Clara Lago) es el nuevo amor de Hache (Mario Casas), pero éste no puede olvidar a su antigua novia, Babi (María Valverde). Hache ha vuelto a casa tras pasar una temporada en Londres, alejado del recuerdo imborrable de aquel primer amor. Para poder reconstruir su vida y olvidar el pasado, Gin parece perfecta, pues es una chica de espíritu descarado, efervescente y vital que le hace creer que es posible revivir aquella magia. Pero tarde o temprano tendrá que encontrarse de nuevo con Babi...','country' =>'España', 'director' =>'Fernando González Molina', 'rating' => 7,'genre_id'=>$genredrama->id],
                ['trailer' => 'https://www.youtube.com/watch?v=9qjHkkffOx8' ,'name'=> 'El orfanato','year' => 2007,'description' => 'Laura se instala con su familia en el orfanato en el que creció de niña. Su propósito es abrir una residencia para niños discapacitados. El ambiente del viejo caserón despierta la imaginación de su hijo, que empieza a dejarse arrastrar por la fantasía. Los juegos del niño inquietan cada vez más a Laura, que empieza a sospechar que en la casa hay algo que amenaza su familia.','country' =>'España', 'director' =>'J.A. Bayona', 'rating' => 8,'genre_id'=>$genreterror->id],
                ['trailer' => 'https://www.youtube.com/watch?v=aurSS82DvCI' ,'name'=> 'Lo imposible','year' => 2012,'description' => 'Diciembre del año 2004. María (Naomi Watts), Henry (Ewan McGregor) y sus tres hijos pequeños vuelan desde Japón a Tailandia para pasar las vacaciones de Navidad en la playa. Una mañana, mientras se encuentran todos en la piscina del complejo a orillas del mar, un tremendo tsunami destroza el hotel y gran parte de la costa del sudeste asiático. Este desastre cambió para siempre la vida de millones de personas. Esta es sólo la historia de una familia.','country' =>'España', 'director' =>'J.A. Bayona', 'rating' => 7,'genre_id'=>$genredrama->id],
                ['trailer' => 'https://www.youtube.com/watch?v=oB1Fw1gdB9Q' ,'name'=> 'Perdiendo el norte','year' => 2015,'description' => 'Hugo y Braulio, dos jóvenes con formación universitaria, hartos de no encontrar ni trabajo ni futuro en España, deciden emigrar a Alemania siguiendo los cantos de sirena de un programa de televisión tipo "Españoles por el mundo". Pero pronto descubrirán que sobrar en un sitio no significa ser necesario en otro y que perseguir el sueño alemán puede tener mucho de pesadilla.','country' =>'España', 'director' =>'Nacho G. Velilla', 'rating' => 5,'genre_id'=>$genrecomedia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=OlK99IuprEQ' ,'name'=> 'Ahora o nunca','year' => 2015,'description' => 'Eva y Alex son una pareja que, tras años de noviazgo, decide casarse en el lugar en el que se enamoraron: un pequeño pueblecito de la campiña inglesa. Los problemas de la boda comienzan cuando una huelga de controladores aéreos impide que el novio y los invitados se reúnan con la novia y su séquito.','country' =>'España', 'director' =>'María Ripoll', 'rating' => 5,'genre_id'=>$genrecomedia->id],
                ['trailer' => 'https://www.youtube.com/watch?v=gpEh4O8Hb5Y' ,'name'=> 'El laberinto del fauno','year' => 2006,'description' => 'Año 1944, posguerra española. Ofelia (Ivana Baquero) y su madre, Carmen (Ariadna Gil), que se encuentra en avanzado estado de gestación, se trasladan a un pequeño pueblo al que ha sido destinado el nuevo marido de Carmen, Vidal (Sergi López), un cruel capitán del ejército franquista por el que la niña no siente ningún afecto. La misión de Vidal es acabar con los últimos miembros de la resistencia republicana que permanecen escondidos en los montes de la zona. Otros personajes son: Mercedes (Maribel Verdú), el ama de llaves, y el médico (Álex Angulo) que se hará cargo del delicado estado de salud de Carmen. Una noche, Ofelia descubre las ruinas de un laberinto, y allí se encuentra con un fauno (Doug Jones), una extraña criatura que le hace una sorprendente revelación: ella es en realidad una princesa, la última de su estirpe, y los suyos la esperan desde hace mucho tiempo. Para poder regresar a su mágico reino, la niña deberá enfrentarse a tres pruebas. ','country' =>'España', 'director' =>'Guillermo del Toro', 'rating' => 8,'genre_id'=>$genrefantasia->id],
            ]
            
        );
    }
}
